set_property PACKAGE_PIN E17 [get_ports {chiplink_tx_data[0]}]
set_property PACKAGE_PIN D18 [get_ports chiplink_tx_rst]
set_property PACKAGE_PIN F17 [get_ports {chiplink_tx_data[1]}]
set_property PACKAGE_PIN F16 [get_ports {chiplink_tx_data[3]}]
set_property PACKAGE_PIN G20 [get_ports {chiplink_tx_data[2]}]
set_property PACKAGE_PIN G19 [get_ports chiplink_tx_send]
set_property PACKAGE_PIN H18 [get_ports {chiplink_tx_data[4]}]
set_property PACKAGE_PIN J18 [get_ports chiplink_tx_clk]
set_property PACKAGE_PIN J20 [get_ports {chiplink_tx_data[5]}]
set_property PACKAGE_PIN H20 [get_ports {chiplink_tx_data[6]}]
set_property PACKAGE_PIN K17 [get_ports {chiplink_tx_data[7]}]
set_property PACKAGE_PIN K18 [get_ports {chiplink_tx_data[8]}]
set_property PACKAGE_PIN G18 [get_ports {chiplink_tx_data[9]}]
set_property PACKAGE_PIN G17 [get_ports {chiplink_tx_data[10]}]
set_property PACKAGE_PIN H17 [get_ports {chiplink_tx_data[11]}]
set_property PACKAGE_PIN H16 [get_ports {chiplink_tx_data[12]}]
set_property PACKAGE_PIN K19 [get_ports {chiplink_tx_data[13]}]
set_property PACKAGE_PIN J19 [get_ports {chiplink_tx_data[14]}]
set_property PACKAGE_PIN G15 [get_ports {chiplink_tx_data[15]}]
set_property PACKAGE_PIN H15 [get_ports {chiplink_tx_data[16]}]
set_property PACKAGE_PIN J14 [get_ports {chiplink_tx_data[17]}]
set_property PACKAGE_PIN K14 [get_ports {chiplink_tx_data[18]}]
set_property PACKAGE_PIN M18 [get_ports {chiplink_tx_data[19]}]
set_property PACKAGE_PIN M17 [get_ports {chiplink_tx_data[20]}]
set_property PACKAGE_PIN A20 [get_ports {chiplink_tx_data[21]}]
set_property PACKAGE_PIN B19 [get_ports {chiplink_tx_data[22]}]
set_property PACKAGE_PIN B20 [get_ports {chiplink_tx_data[23]}]
set_property PACKAGE_PIN C20 [get_ports {chiplink_tx_data[24]}]
set_property PACKAGE_PIN D19 [get_ports {chiplink_tx_data[26]}]
set_property PACKAGE_PIN D20 [get_ports {chiplink_tx_data[25]}]
set_property PACKAGE_PIN E19 [get_ports {chiplink_tx_data[27]}]
set_property PACKAGE_PIN E18 [get_ports {chiplink_tx_data[28]}]
set_property PACKAGE_PIN F20 [get_ports {chiplink_tx_data[29]}]
set_property PACKAGE_PIN F19 [get_ports {chiplink_tx_data[30]}]
set_property PACKAGE_PIN N20 [get_ports chiplink_rx_clk]
set_property PACKAGE_PIN P20 [get_ports chiplink_rx_rst]
set_property PACKAGE_PIN T16 [get_ports {chiplink_rx_data[28]}]
set_property PACKAGE_PIN U17 [get_ports {chiplink_rx_data[29]}]
set_property PACKAGE_PIN P19 [get_ports {chiplink_rx_data[27]}]
set_property PACKAGE_PIN Y16 [get_ports {chiplink_rx_data[26]}]
set_property PACKAGE_PIN V15 [get_ports {chiplink_rx_data[24]}]
set_property PACKAGE_PIN Y17 [get_ports {chiplink_rx_data[25]}]
set_property PACKAGE_PIN W15 [get_ports {chiplink_rx_data[23]}]
set_property PACKAGE_PIN Y14 [get_ports {chiplink_rx_data[22]}]
set_property PACKAGE_PIN W14 [get_ports {chiplink_rx_data[21]}]
set_property PACKAGE_PIN U15 [get_ports {chiplink_rx_data[20]}]
set_property PACKAGE_PIN U14 [get_ports {chiplink_rx_data[19]}]
set_property PACKAGE_PIN R14 [get_ports {chiplink_rx_data[18]}]
set_property PACKAGE_PIN P14 [get_ports {chiplink_rx_data[17]}]
set_property PACKAGE_PIN T14 [get_ports {chiplink_rx_data[16]}]
set_property PACKAGE_PIN T15 [get_ports {chiplink_rx_data[15]}]
set_property PACKAGE_PIN U13 [get_ports {chiplink_rx_data[14]}]
set_property PACKAGE_PIN V13 [get_ports {chiplink_rx_data[13]}]
set_property PACKAGE_PIN W13 [get_ports {chiplink_rx_data[12]}]
set_property PACKAGE_PIN V12 [get_ports {chiplink_rx_data[11]}]
set_property PACKAGE_PIN T12 [get_ports {chiplink_rx_data[10]}]
set_property PACKAGE_PIN U12 [get_ports {chiplink_rx_data[9]}]
set_property PACKAGE_PIN T11 [get_ports {chiplink_rx_data[8]}]
set_property PACKAGE_PIN T10 [get_ports {chiplink_rx_data[7]}]
set_property PACKAGE_PIN P18 [get_ports {chiplink_rx_data[1]}]
set_property PACKAGE_PIN N17 [get_ports {chiplink_rx_data[0]}]
set_property PACKAGE_PIN P15 [get_ports {chiplink_rx_data[2]}]
set_property PACKAGE_PIN P16 [get_ports {chiplink_rx_data[3]}]
set_property PACKAGE_PIN T17 [get_ports {chiplink_rx_data[4]}]
set_property PACKAGE_PIN R18 [get_ports {chiplink_rx_data[5]}]
set_property PACKAGE_PIN U20 [get_ports {chiplink_rx_data[6]}]
set_property PACKAGE_PIN T20 [get_ports {chiplink_rx_data[30]}]
set_property PACKAGE_PIN R17 [get_ports {chiplink_rx_data[31]}]
set_property PACKAGE_PIN L15 [get_ports {chiplink_tx_data[31]}]
set_property PACKAGE_PIN N18 [get_ports chiplink_rx_send]
set_property PACKAGE_PIN L14 [get_ports chiplink_cpu_int]

set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports chiplink_cpu_int]
set_property IOSTANDARD LVCMOS33 [get_ports chiplink_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports chiplink_rx_rst]
set_property IOSTANDARD LVCMOS33 [get_ports chiplink_tx_send]
set_property IOSTANDARD LVCMOS33 [get_ports chiplink_rx_send]
set_property IOSTANDARD LVCMOS33 [get_ports chiplink_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports chiplink_tx_rst]


# create_clock -period 40.000 -name chiplink_tx_clk -waveform {0.000 20.000} [get_ports {chiplink_tx_clk}]
# create_generated_clock -name chiplink_tx_clk -edges {1 2 3} -source [get_pins {design_1_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] [get_ports chiplink_tx_clk]
create_generated_clock -name chiplink_tx_clk -source [get_pins design_1_i/chiplink_ctrl_0/clk] -divide_by 1 [get_ports chiplink_tx_clk]
# create_generated_clock -name chiplink_tx_clk -edges {1 2 3} -source [get_clocks clk_fpga_0] [get_ports chiplink_tx_clk]
set_input_delay -clock [get_clocks chiplink_tx_clk] -min -add_delay 0.680 [get_ports {chiplink_tx_data[*]}]
set_input_delay -clock [get_clocks chiplink_tx_clk] -max -add_delay 2.500 [get_ports {chiplink_tx_data[*]}]
set_input_delay -clock [get_clocks chiplink_tx_clk] -min -add_delay 0.680 [get_ports chiplink_tx_rst]
set_input_delay -clock [get_clocks chiplink_tx_clk] -max -add_delay 2.500 [get_ports chiplink_tx_rst]
set_input_delay -clock [get_clocks chiplink_tx_clk] -min -add_delay 0.680 [get_ports chiplink_tx_send]
set_input_delay -clock [get_clocks chiplink_tx_clk] -max -add_delay 2.500 [get_ports chiplink_tx_send]

create_clock -period 40.000 -name chiplink_rx_clk -waveform {0.000 20.000}
set_output_delay -clock [get_clocks chiplink_rx_clk] -min -add_delay 0.680 [get_ports {chiplink_rx_data[*]}]
set_output_delay -clock [get_clocks chiplink_rx_clk] -max -add_delay 2.500 [get_ports {chiplink_rx_data[*]}]
set_output_delay -clock [get_clocks chiplink_rx_clk] -min -add_delay 0.680 [get_ports chiplink_rx_rst]
set_output_delay -clock [get_clocks chiplink_rx_clk] -max -add_delay 2.500 [get_ports chiplink_rx_rst]
set_output_delay -clock [get_clocks chiplink_rx_clk] -min -add_delay 0.680 [get_ports chiplink_rx_send]
set_output_delay -clock [get_clocks chiplink_rx_clk] -max -add_delay 2.500 [get_ports chiplink_rx_send]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[1]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[2]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[3]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[4]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[5]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[6]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[7]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[8]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[9]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[10]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[11]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[12]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[13]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[14]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[15]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[16]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[17]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[18]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[19]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[20]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[21]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[22]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[23]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[24]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[25]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[26]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[27]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[28]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[29]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[30]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWADDR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_AWBURST[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWBURST[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_ARLEN[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARLEN[1]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARLEN[2]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARLEN[3]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARLEN[4]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARLEN[5]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARLEN[6]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARLEN[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 3 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_AWSIZE[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWSIZE[1]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWSIZE[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_AWLEN[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWLEN[1]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWLEN[2]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWLEN[3]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWLEN[4]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWLEN[5]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWLEN[6]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWLEN[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 2 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_BRESP[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_BRESP[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 4 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_ARID[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARID[1]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARID[2]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARID[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 2 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_RRESP[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RRESP[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 8 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_WSTRB[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WSTRB[1]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WSTRB[2]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WSTRB[3]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WSTRB[4]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WSTRB[5]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WSTRB[6]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WSTRB[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 3 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_ARSIZE[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARSIZE[1]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARSIZE[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 4 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_AWID[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWID[1]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWID[2]} {design_1_i/chiplink_ctrl_0_io_axi4_0_AWID[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 4 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_BID[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_BID[1]} {design_1_i/chiplink_ctrl_0_io_axi4_0_BID[2]} {design_1_i/chiplink_ctrl_0_io_axi4_0_BID[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 64 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[1]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[2]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[3]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[4]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[5]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[6]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[7]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[8]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[9]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[10]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[11]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[12]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[13]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[14]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[15]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[16]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[17]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[18]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[19]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[20]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[21]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[22]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[23]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[24]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[25]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[26]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[27]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[28]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[29]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[30]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[31]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[32]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[33]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[34]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[35]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[36]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[37]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[38]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[39]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[40]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[41]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[42]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[43]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[44]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[45]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[46]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[47]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[48]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[49]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[50]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[51]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[52]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[53]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[54]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[55]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[56]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[57]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[58]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[59]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[60]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[61]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[62]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RDATA[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[1]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[2]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[3]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[4]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[5]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[6]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[7]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[8]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[9]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[10]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[11]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[12]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[13]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[14]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[15]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[16]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[17]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[18]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[19]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[20]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[21]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[22]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[23]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[24]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[25]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[26]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[27]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[28]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[29]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[30]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARADDR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 2 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_ARBURST[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_ARBURST[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 64 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[1]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[2]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[3]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[4]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[5]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[6]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[7]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[8]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[9]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[10]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[11]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[12]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[13]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[14]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[15]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[16]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[17]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[18]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[19]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[20]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[21]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[22]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[23]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[24]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[25]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[26]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[27]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[28]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[29]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[30]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[31]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[32]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[33]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[34]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[35]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[36]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[37]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[38]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[39]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[40]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[41]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[42]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[43]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[44]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[45]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[46]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[47]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[48]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[49]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[50]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[51]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[52]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[53]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[54]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[55]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[56]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[57]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[58]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[59]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[60]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[61]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[62]} {design_1_i/chiplink_ctrl_0_io_axi4_0_WDATA[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 4 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {design_1_i/chiplink_ctrl_0_io_axi4_0_RID[0]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RID[1]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RID[2]} {design_1_i/chiplink_ctrl_0_io_axi4_0_RID[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 32 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {chiplink_rx_data_OBUF[0]} {chiplink_rx_data_OBUF[1]} {chiplink_rx_data_OBUF[2]} {chiplink_rx_data_OBUF[3]} {chiplink_rx_data_OBUF[4]} {chiplink_rx_data_OBUF[5]} {chiplink_rx_data_OBUF[6]} {chiplink_rx_data_OBUF[7]} {chiplink_rx_data_OBUF[8]} {chiplink_rx_data_OBUF[9]} {chiplink_rx_data_OBUF[10]} {chiplink_rx_data_OBUF[11]} {chiplink_rx_data_OBUF[12]} {chiplink_rx_data_OBUF[13]} {chiplink_rx_data_OBUF[14]} {chiplink_rx_data_OBUF[15]} {chiplink_rx_data_OBUF[16]} {chiplink_rx_data_OBUF[17]} {chiplink_rx_data_OBUF[18]} {chiplink_rx_data_OBUF[19]} {chiplink_rx_data_OBUF[20]} {chiplink_rx_data_OBUF[21]} {chiplink_rx_data_OBUF[22]} {chiplink_rx_data_OBUF[23]} {chiplink_rx_data_OBUF[24]} {chiplink_rx_data_OBUF[25]} {chiplink_rx_data_OBUF[26]} {chiplink_rx_data_OBUF[27]} {chiplink_rx_data_OBUF[28]} {chiplink_rx_data_OBUF[29]} {chiplink_rx_data_OBUF[30]} {chiplink_rx_data_OBUF[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 32 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {chiplink_tx_data_IBUF[0]} {chiplink_tx_data_IBUF[1]} {chiplink_tx_data_IBUF[2]} {chiplink_tx_data_IBUF[3]} {chiplink_tx_data_IBUF[4]} {chiplink_tx_data_IBUF[5]} {chiplink_tx_data_IBUF[6]} {chiplink_tx_data_IBUF[7]} {chiplink_tx_data_IBUF[8]} {chiplink_tx_data_IBUF[9]} {chiplink_tx_data_IBUF[10]} {chiplink_tx_data_IBUF[11]} {chiplink_tx_data_IBUF[12]} {chiplink_tx_data_IBUF[13]} {chiplink_tx_data_IBUF[14]} {chiplink_tx_data_IBUF[15]} {chiplink_tx_data_IBUF[16]} {chiplink_tx_data_IBUF[17]} {chiplink_tx_data_IBUF[18]} {chiplink_tx_data_IBUF[19]} {chiplink_tx_data_IBUF[20]} {chiplink_tx_data_IBUF[21]} {chiplink_tx_data_IBUF[22]} {chiplink_tx_data_IBUF[23]} {chiplink_tx_data_IBUF[24]} {chiplink_tx_data_IBUF[25]} {chiplink_tx_data_IBUF[26]} {chiplink_tx_data_IBUF[27]} {chiplink_tx_data_IBUF[28]} {chiplink_tx_data_IBUF[29]} {chiplink_tx_data_IBUF[30]} {chiplink_tx_data_IBUF[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list design_1_i/chiplink_ctrl_0_io_axi4_0_ARREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list design_1_i/chiplink_ctrl_0_io_axi4_0_ARVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list design_1_i/chiplink_ctrl_0_io_axi4_0_AWREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list design_1_i/chiplink_ctrl_0_io_axi4_0_AWVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list design_1_i/chiplink_ctrl_0_io_axi4_0_BREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list design_1_i/chiplink_ctrl_0_io_axi4_0_BVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list design_1_i/chiplink_ctrl_0_io_axi4_0_RLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list design_1_i/chiplink_ctrl_0_io_axi4_0_RREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list design_1_i/chiplink_ctrl_0_io_axi4_0_RVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list design_1_i/chiplink_ctrl_0_io_axi4_0_WLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list design_1_i/chiplink_ctrl_0_io_axi4_0_WREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list design_1_i/chiplink_ctrl_0_io_axi4_0_WVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list chiplink_rx_rst_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list chiplink_rx_send_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list chiplink_tx_clk_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list chiplink_tx_rst_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list chiplink_tx_send_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets chiplink_rx_clk_OBUF]
